version: "3"

x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '3.2.2'
      PG_MAJOR: '15'
      NODE_MAJOR: '18'
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  environment: &backend_environment
    <<: *env
    REDIS_URL: redis://redis:6379/0
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: database
  volumes:
      - .:/app
      - backend_data:/usr/local/bundle
  depends_on: &backend_depends_on
    database:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  database:
    hostname: database-app-container
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  web:
    <<: *backend
    hostname: web-app-container
    ports:
      - "3000:3000"
    depends_on:
      sidekiq:
        condition: service_started
  sidekiq:
    <<: *backend
    hostname: sidekiq-app-container
    command: /app/bin/bundle exec sidekiq
  redis:
    image: docker.io/redis:latest
    hostname: redis
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  backend_data:
  database-data:
    driver: local
